kind: pipeline
type: docker
name: CI
 
trigger:
  event:
    - push

steps:
  - name: build
    image: swift:latest
    commands:
      - cd ./Sources/Model/
      - swift build
      - cd ../CommandLineExt/
      - swift build
      - cd ../CommandLineTest/
      - swift build

  - name: tests
    image: swift:latest
    commands:
      - cd ./Sources/Model/
      - swift test
    depends_on: [build]
