kind: pipeline
type: docker
name: CI
 
trigger:
  event:
    - push

steps:
  - name: build
    image: swift:latest
    commands:
      - cd ./Sources/Model/
      - swift build
      - cd ../CommandLineExt/
      - swift build
      - cd ../CommandLineTest/
      - swift build

  - name: tests
    image: swift:latest
    commands:
      - cd ./Sources/Model/
      - swift test --enable-code-coverage
      - ./coverage.sh
    depends_on: [build]

  - name: analysis
    image: hub.codefirst.iut.uca.fr/axel.de_la_fuente/codefirst-dronesonarplugin-swift
    commands:
      - sonar-scanner -Dsonar.projectKey=DouShouQi -Dsonar.sources=. -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar -Dsonar.login=$${PLUGIN_SONAR_TOKEN}
    depends_on: [tests]
