kind: pipeline
type: docker
name: CI
 
trigger:
  event:
    - push

steps:
  - name: build
    image: swift:latest
    commands:
      - cd ./Sources/Model/
      - swift build
      - cd ../CommandLineExt/
      - swift build
      - cd ../CommandLineTest/
      - swift build

  - name: tests
    image: swift:latest
    commands:
      - cd ./Sources/Model/
      - swift test --enable-code-coverage
      - ./coverage.sh
    depends_on: [build]

  - name: analysis
    image: sonarsource/sonar-scanner-cli:latest
    commands:
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"

      - sonar-scanner -Dsonar.projectKey=DouShouQi -Dsonar.sources=. -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar -Dsonar.login=$${PLUGIN_SONAR_TOKEN}
    depends_on: [tests]
